### PR TITLE
debian: update dependencies

### PR DESCRIPTION
**Pull request by wsldankers**
Add meson because it's necessary for several components, nasm because libass doesn't support yasm anymore (and it's reportedly better anyway) and some dependencies to support wayland.

Also bump the dh compat level (9 has been deprecated for a while now).

### CODE REVIEW

**Comment by avih** [comment]
> Add meson because it's necessary for several components

Which ones, other than libplacebo? What happened with them till now? broken?

> Also bump the dh compat level (9 has been deprecated for a while now).

Does this affect the minimum supported version of debian? regardless, what's currently/with-the-patch the minimum debian version?

**Comment by wsldankers** [comment]
Well mpv itself builds using meson by default these days (mpv git warns about waf being a deprecated build system) so this change paves the way for switching over to meson for mpv as well.

Compat level 13 corresponds to debhelper 13, which is in Debian stable (and oldstable if you use the official Debian backports). Likewise it's in Ubuntu LTS 22.04 (and LTS 20.04 if you use the official Ubuntu backports).
Trying to compile mpv for such old versions is tricky at best so I feel confident in bumping the dh compat level to the recommended level.

https://packages.debian.org/debhelper
https://packages.ubuntu.com/debhelper

**Comment by avih** [comment]
Thanks.

**Comment by avih** [comment]
For future reference, it turns out that the meson version in debian stable is not enough to build libplacebo (or mpv, when we'll update the build script).

So basically adding meson as a dependency doesn't particularly help, but can hurt those which look at this commit and expect it to actually work with stable.

So keep that in mind.

It could be nice if mpv-build could support downloading a curated version of meson, if possible, similar to how the (non-meson) mpv build process downloads waf.

**Comment by wsldankers** [comment]
It's still useful for people like me who do automated builds and have something PPA-like configured to get a more recent version of meson.

**Pull request merged**
